# number = input("Enter a four_digit number: ")
# print(number[0])
# print(number[1])
# print(number[2])
# print(number[-1])

number = int(input("Enter a four_digit number: "))
a, number = divmod(number, 1000)
b, number = divmod(number, 100)
c, d = divmod(number, 10)

print(a)
print(b)
print(c)
print(d)