# number = input("Enter a four_digit number: ")
# print(number[0])
# print(number[1])
# print(number[2])
# print(number[-1])

number = int(input("Enter a four_digit number: "))
number, x4 = divmod(number, 10)
number, x3 = divmod(number, 10)
number, x2 = divmod(number, 10)
number, x1 = divmod(number, 10)
print(x1)
print(x2)
print(x3)
print(x4)